Adding S3ArchiveSync construct
pahud/cdk-efs-assets pull request #52
Opened 2020-12-25 23:20 UTC by stephenwiebe

This adds a construct that can be used to sync data stored in an S3 zip file to an EFS filesystem.

2020-12-26 04:57 UTC, pahud commented
Thank you for your contribution. Will look into it shortly.

2020-12-27 07:30 UTC, pahud requested changes
LGTM. Just one minor suggestion.

2020-12-27 07:30 UTC, pahud commented on src/s3-archive-sync.ts
> +  readonly shouldMonitorS3Path?: boolean;
```suggestion
  readonly syncOnUpdate?: boolean;
```

How about `syncOnUpdate`, which is more straigit-forward?

2020-12-28 03:13 UTC, stephenwiebe commented on src/s3-archive-sync.ts
> +  readonly shouldMonitorS3Path?: boolean;
That makes sense, I went ahead and updated that.

2020-12-28 03:27 UTC, pahud commented
@stephenwiebe we're almost there. Can you fix the conflicts ? thanks.

2020-12-28 03:55 UTC, stephenwiebe commented
> @stephenwiebe we're almost there. Can you fix the conflicts ? thanks.

Should be good now, I think.

2020-12-28 23:24 UTC, pahud commented
> edit: Looks like the build failed due to a tamper check... I'm not quite sure what the problem is...

It's due to the `yarn upgrade` I think.

Can you run `npx projen` again? It should fix the newline locally and you can commit again.

this will fix the anti-tamper error.

2020-12-29 00:20 UTC, stephenwiebe commented
> Can you run `npx projen` again? It should fix the newline locally and you can commit again.
> 
> this will fix the anti-tamper error.

Ok, thanks, this looks to be fixed now.

2020-12-29 01:09 UTC, pahud requested changes
we're almost there. One last minor sugestion.

2020-12-29 01:09 UTC, pahud commented on README.md
> +});
```suggestion
new S3ArchiveSync(this, 'S3ArchiveSync', {
  bucket,
  zipFilePath: 'folder/foo.zip',
  vpc,
  efsAccessPoint,
  runsAfter: [fs.mountTargetsAvailable],
});
```

Let's make it looks cleaner this way, what do you think?

2020-12-29 01:31 UTC, pahud approved these changes

2020-12-29 01:41 UTC, pahud commented
Hi @stephenwiebe 

Can you run `yarn upgrade && npx projen && yarn bulid` and commit everything updated again?

I think this will help us pass the anti-tamper check.

2020-12-29 03:11 UTC, merged

2020-12-29 03:23 UTC, pahud commented
Thank you so much! I will create a tweet to celebrate this!

@stephenwiebe

2020-12-29 03:27 UTC, stephenwiebe commented
Sweet! Thanks for your help getting it merged in.