Refactor to expose functionality as SyncedAccessPoint
pahud/cdk-efs-assets pull request #62
Opened 2021-01-04 18:53 UTC by stephenwiebe

As discussed in #55, I think this refactor exposes the sync functionality in a more "CDK" appropriate way. It removes the capability to sync data to an arbitrary AccessPoint, but I think that makes sense as discussed in the issue above - most importantly because the sync is potentially destructive to any existing data so users should not attempt to use an AccessPoint that has existing content.

I haven't yet updated the README.md but you can see how to use it in integ.default.ts.

Let me know what you think. If you agree, the minor version number should probably be bumped from 0.1 to 0.2 as this changeset would break backward compatibility.

Fixes #55

2021-01-05 08:18 UTC, guan840912 requested changes

2021-01-05 08:52 UTC, pahud commented on src/synced-access-point.ts
> +      vpcSubnets: vpcSubnets,
Thanks @guan840912 let's improve this in another PR.

2021-01-05 08:54 UTC, pahud commented
Hi @stephenwiebe LGTM. 

Feel free to continue this PR. Thanks.

2021-01-11 05:52 UTC, stephenwiebe commented
@pahud Ok, I think this is ready now. Do you want to take another look and merge in if everything looks good? BTW, I added an optional syncDirectoryPath property because I noticed the default directory behavior of the Github source and the S3 source were different. The behavior is more unified now and the user can now specify an output directory to sync into rather than relying on just the default behavior, if they wish.

2021-01-11 05:54 UTC, stephenwiebe commented
Oh, and I also updated the version to 0.2.0 because it would break compatibility with 0.1.x.

2021-01-15 06:22 UTC, stephenwiebe commented
@pahud Any word on this? Just wanted to bump this in case you had missed it.

2021-01-16 12:40 UTC, guan840912 reviewed
cc @pahud

2021-01-16 12:40 UTC, guan840912 commented on src/synced-access-point.ts
> +      syncDirectoryPath = '/' + splitDirs[splitDirs.length - 1].split('.')[0];
how about using `path.basename`  instead of  `.split('.')[0];`. 😊
like this:
```ts
syncDirectoryPath = '/' + path.basename(splitDirs[splitDirs.length - 1], '.git');
```

2021-01-18 06:54 UTC, stephenwiebe commented on src/synced-access-point.ts
> +      syncDirectoryPath = '/' + splitDirs[splitDirs.length - 1].split('.')[0];
Thanks for the suggestion, I updated this.

2021-01-18 07:12 UTC, guan840912 reviewed
LGTM

2021-01-18 07:20 UTC, pahud approved these changes

2021-01-18 07:21 UTC, pahud commented
Sorry for the late review. LGTM.

Can you please resolve the conflicts before we get it merged? Thanks.

2021-01-18 07:50 UTC, pahud commented
@stephenwiebe please update the `yarn.lock` as well by running `yarn upgrade && npx projen`

2021-01-18 07:56 UTC, merged